name = "LDAPClient"
uuid = "a3dbcd64-d9cb-45e9-b48d-422bbbdd8627"
license = "MIT"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
repo = "https://github.com/felipenoris/LDAP.jl.git"
version = "0.1.1"

[deps]
OpenLDAPClient_jll = "234f2d50-f964-585e-b1c8-17cd4567e563"

[compat]
OpenLDAPClient_jll = "2.4"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
