
@enum LDAPVersion::Cint begin
    LDAP_VERSION1 = 1
    LDAP_VERSION2 = 2
    LDAP_VERSION3 = 3
end

@enum LDAPOption::UInt16 begin
    LDAP_OPT_PROTOCOL_VERSION = 0x0011
end

@enum LDAPMessageType::UInt8 begin
    LDAP_RES_BIND = 0x61
    LDAP_RES_SEARCH_ENTRY = 0x64
    LDAP_RES_SEARCH_REFERENCE = 0x73
    LDAP_RES_SEARCH_RESULT = 0x65
    LDAP_RES_MODIFY = 0x67
    LDAP_RES_ADD = 0x69
    LDAP_RES_DELETE = 0x6b
    LDAP_RES_MODDN = 0x6d
    LDAP_RES_COMPARE = 0x6f
    LDAP_RES_EXTENDED = 0x78
    LDAP_RES_INTERMEDIATE = 0x79
end

@enum LDAPScope::Cint begin
    LDAP_SCOPE_BASE = 0x0000
    LDAP_SCOPE_ONELEVEL = 0x0001
    LDAP_SCOPE_SUBTREE = 0x0002
    LDAP_SCOPE_CHILDREN = 0x0003
end
